name: 'leap_case'
version: '2.0.0'
config-version: 2

profile: 'leap_case'  # Ensure your ~/.dbt/profiles.yml points to SALES_DB

models:
  leap_case:
    +materialized: view

    staging:
      +schema: STAGING
      +materialized: view

    transform_data:
      +schema: TRANSFORM_DATA
      +materialized: table
      +on_schema_change: "sync_all_columns"

    analytics:
      +schema: ANALYTICS
      +materialized: table

quoting:
  database: false
  schema: false
  identifier: false

macro-paths: ["macros"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]
