version: 2

sources:
  - name: raw_data
    database: SALES_DB
    schema: RAW_DATA
    tables:
      - name: manufacturers
      - name: products
      - name: customers
      - name: inventory
      - name: sales
      - name: sales_line_items
